const figures=[
['The stable patient with VT','Normal blood pressure and mentation do not exclude VT. Look for AV dissociation, extreme axis, broad QRS and V6 R/S <1.',440],
['Six mechanisms of wide QRS tachycardia','Left to right: VT, aberrant conduction, pre-excitation, abnormal baseline QRS, drug/electrolyte widening, ventricular pacing. Each has LBBB-like and RBBB-like V1/V6 examples.',440],
['Precordial concordance','Positive and negative concordance in VT. Concordance supports VT but is not absolute proof; positive concordance can occur with accessory pathways.',444],
['Capture and fusion beats','A capture beat reflects supraventricular activation during VT; fusion combines ventricular and supraventricular activation. Confirm the atrial relationship and exclude mimics.',445],
['V1 and V6 morphology','Compare typical aberrancy with VT patterns in RBBB-like and LBBB-like tachycardias. Assess both leads, not only QRS width.',446],
['Unusual V1 configurations','Rs and W configurations illustrated in the article favor VT over conventional aberrancy. Baseline disease and pre-excitation need separate assessment.',446],
['Why the V6 R/S ratio matters','In RBBB-like WCT, a dominant S wave in V6 (R/S <1) favors VT; typical RBBB usually preserves a dominant R wave.',447],
['Absent RS — an important exception','The article includes VT examples and a bottom-panel LBBB SVT example with no precordial RS. This criterion is not perfectly specific.',448],
['Alternans can occur in VT','Beat-to-beat QRS amplitude variation is not a reliable distinction between VT and SVT. This tracing shows alternans during VT.',449]
];
const conditions=[
{title:'Ventricular tachycardia',tag:'VENTRICULAR ORIGIN',text:'Ventricular activation may proceed through myocardium instead of normal His–Purkinje conduction. Structural heart disease raises suspicion, but idiopathic VT can occur in a normal heart.',points:['AV dissociation; ventricular activity independent of atrial activity.','True capture or fusion beats.','VT-compatible morphology in V1/V2 and V6; concordance; extreme axis.','A stable patient can still have sustained VT. A 1:1 VA relationship does not exclude VT.'],fig:1,extra:5},
{title:'SVT with aberrancy',tag:'SUPRAVENTRICULAR ORIGIN',text:'An atrial or AV-junctional tachycardia is conducted with pre-existing or rate-related bundle branch block. AVNRT, orthodromic AVRT, atrial tachycardia and flutter can all appear wide when aberrancy is present.',points:['Typical RBBB: often rsR′ in V1 and a dominant R with terminal S in V6.','Typical LBBB: negative V1 and broad predominantly positive V6; a V6 q wave is atypical.','An identical baseline QRS supports aberrancy, with exceptions including bundle branch reentry VT.','Rate near 150 bpm may prompt a search for flutter, but rate alone cannot classify WCT.'],fig:2,extra:5},
{title:'Pre-excited tachycardia',tag:'ACCESSORY PATHWAY',text:'An accessory pathway activates ventricular myocardium outside the normal conduction system. Antidromic AVRT may be regular and wide; pre-excited AF may be irregular with varying QRS shapes.',points:['Figure 2, third column, illustrates pre-excitation in V1/V6.','Look for baseline short PR and delta waves; their absence on an available tracing does not exclude an accessory pathway.','Pre-excitation can mimic VT morphology, so VT-versus-aberrancy rules do not establish the mechanism.','Irregular pre-excited rhythms require urgent expert care; avoid empiric AV nodal blockade.'],fig:2},
{title:'Abnormal baseline QRS',tag:'BASELINE CONDUCTION DISEASE',text:'Cardiomyopathy or repaired congenital heart disease can produce unusual baseline activation. A supraventricular rhythm may retain this broad, atypical QRS.',points:['Figure 2, fourth column, shows abnormal baseline QRS examples.','Compare a prior 12-lead ECG at baseline.','A matching QRS supports a baseline conduction mechanism but does not prove SVT.','A narrower QRS during tachycardia or contralateral BBB can favor VT, with conduction-delay exceptions.'],fig:2},
{title:'Drug / electrolyte widening',tag:'REVERSIBLE CONTRIBUTORS',text:'Hyperkalemia, acidosis and sodium-channel-blocking drug effects can widen an otherwise supraventricular rhythm. These conditions may also provoke ventricular arrhythmia.',points:['Figure 2, fifth column, shows nonspecific widening examples, not a diagnosis of a particular toxin.','Review potassium, renal function, acid-base status and medications or exposure history.','Peaked T waves can support hyperkalemia; ECG appearance alone cannot rule it out.','QRS-duration thresholds lose specificity when drug or metabolic effects are present.'],fig:2},
{title:'Ventricular pacing',tag:'DEVICE-RELATED RHYTHM',text:'Ventricular pacing produces a wide QRS and may track atrial tachycardia or occur during device-mediated tachycardia. Patients with a device can also develop independent VT.',points:['Figure 2, rightmost column, shows ventricular-paced V1/V6 examples.','Search for pacing artifacts; modern low-output spikes can be hard to see.','Compare prior paced morphology and arrange device interrogation.','The presence of a pacemaker does not establish that a wide tachycardia is paced.'],fig:2},
{title:'Polymorphic VT / torsades',tag:'EMERGENCY DIFFERENTIAL',text:'QRS configuration changes beat to beat. A prolonged baseline QT supports torsades de pointes; a normal QT suggests another polymorphic VT mechanism, including acute ischemia.',points:['Sustained polymorphic VT requires immediate unsynchronized shock under AHA 2025 guidance.','Do not apply Brugada morphology criteria or give adenosine to polymorphic WCT.','Review baseline QT, potassium, magnesium and QT-prolonging medicines.','No dedicated polymorphic VT or torsades ECG is supplied in this PDF. The monomorphic examples must not be relabeled as torsades.'],fig:null}
];
const criteria=[['av','AV dissociation'],['capture','True capture or fusion beats'],['noRS','No RS complex in any of V1–V6'],['rs100','RS interval >100 ms in any chest lead'],['morphvt','VT morphology in V1/V2 and V6'],['axis','Extreme right-superior QRS axis'],['concordance','All chest leads predominantly same polarity'],['baseline','QRS identical to baseline tracing']];
const alternatives=[['preexcitation','Accessory pathway / pre-excitation suspected'],['pacing','Ventricular pacing suspected'],['metabolic','Drug or electrolyte widening suspected']];
function controls(items){return items.map(([key,label])=>`<label>${label}<select name="${key}"><option value="unknown">Unknown / not assessed</option><option value="yes">Yes</option><option value="no">No</option></select></label>`).join('')}
document.querySelector('#criteria').innerHTML=controls(criteria);document.querySelector('#alternatives').innerHTML=controls(alternatives);
function figure(n){let f=figures[n-1];return `<img class="figure" tabindex="0" role="button" data-figure="${n}" src="assets/figure-${n}.webp" alt="Figure ${n}: ${f[0]}" loading="lazy"><p class="figure-note">Figure ${n} · Miller et al., 2006 · p. ${f[2]} · Select to enlarge</p>`}
function condition(i){const c=conditions[i];document.querySelector('#condition-detail').innerHTML=`<span class="pill">${c.tag}</span><h2>${c.title}</h2><p>${c.text}</p><ul>${c.points.map(p=>`<li>${p}</li>`).join('')}</ul>${c.fig?figure(c.fig):'<div class="notice">Image gap: the attached article does not contain a dedicated tracing for this condition.</div>'}${c.extra?figure(c.extra):''}`;document.querySelectorAll('.condition-button').forEach((b,n)=>b.classList.toggle('active',n===i))}
document.querySelector('#condition-buttons').innerHTML=conditions.map((c,i)=>`<button class="condition-button" data-condition="${i}">${c.title}</button>`).join('');condition(0);
const lessons=[['AV dissociation','P waves march independently of QRS complexes. Absence of visible dissociation is common and does not rule out VT. A 1:1 atrioventricular relationship can occur during VT.',4],['Capture & fusion','Identify atrial timing and a true captured or hybrid complex. Premature beats, variable aberrancy and pre-excitation may mimic these appearances.',4],['RBBB-like morphology','VT clues include a monophasic R or qR in V1 and R/S <1 in V6. A typical rsR′ with dominant terminal R in V1 favors aberrancy; unusual Rs/W patterns favor VT.',5],['LBBB-like morphology','An initial R >30 ms, QRS onset to S nadir >60 ms or notching in the descending S in V1/V2 favors VT. A q wave or QS in V6 also favors VT.',5],['Duration and axis','Historical supportive thresholds: RBBB-like QRS >140 ms, LBBB-like QRS >160 ms. Extreme right-superior axis supports VT. Neither is diagnostic alone.',1],['Concordance','All chest-lead QRS complexes predominantly positive or negative support VT. Assess pre-excitation and baseline abnormalities; exceptions exist.',3],['Brugada RS criteria','Look for an RS in each chest lead. If present, measure R onset to S nadir; >100 ms supports VT. The article demonstrates an SVT exception to absent RS.',8],['Baseline comparison and alternans','Identical baseline morphology supports aberrancy but does not exclude bundle branch reentry VT. Alternans and normal blood pressure cannot reliably classify the rhythm.',9]];
document.querySelector('#lesson-cards').innerHTML=lessons.map(([t,p,f])=>`<article class="card"><h3>${t}</h3><p>${p}</p><a href="#" data-open="${f}">View ECG example →</a></article>`).join('');
document.querySelector('#atlas-grid').innerHTML=figures.map((f,i)=>`<article class="card"><span class="pill">FIGURE ${i+1}</span><h3>${f[0]}</h3>${figure(i+1)}<p>${f[1]}</p></article>`).join('');
const names={analyze:['Analyze wide QRS tachycardia','Work through clinical context and ECG findings. Every conclusion shows its supporting criteria.'],learn:['Learn the wide QRS differential','Connect each ECG finding to its mechanism, its diagnostic value and its exceptions.'],atlas:['ECG image atlas','Nine original figures from the attached article, linked to the conditions and criteria they illustrate.'],sources:['References & clinical scope','A transparent source trail and the limits of this educational tool.']};
function show(tab){Object.keys(names).forEach(k=>document.getElementById(k).hidden=k!==tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelector('#page-title').textContent=names[tab][0];document.querySelector('#intro').textContent=names[tab][1];window.scrollTo(0,0)}
function openFigure(n){const f=figures[n-1];document.querySelector('#dialog-title').textContent=`Figure ${n}: ${f[0]}`;const im=document.querySelector('#dialog-image');im.src=`assets/figure-${n}.webp`;im.alt=f[0];document.querySelector('#dialog-caption').textContent=f[1]+` Source: Miller et al., 2006, p. ${f[2]}.`;document.querySelector('#image-dialog').showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-tab],[data-go],[data-condition],[data-figure],[data-open]');if(!b)return;e.preventDefault();if(b.dataset.tab||b.dataset.go)show(b.dataset.tab||b.dataset.go);else if(b.dataset.condition!==undefined)condition(Number(b.dataset.condition));else openFigure(Number(b.dataset.figure||b.dataset.open))});document.addEventListener('keydown',e=>{if(e.target.dataset.figure&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openFigure(Number(e.target.dataset.figure))}});document.querySelector('#close-dialog').onclick=()=>document.querySelector('#image-dialog').close();
let imageURL;function clearImage(){if(imageURL)URL.revokeObjectURL(imageURL);imageURL=null;document.querySelector('#ecg-preview').hidden=true;document.querySelector('#ecg-preview').removeAttribute('src');document.querySelector('#ecg-upload').value='';document.querySelector('#remove-image').hidden=true}document.querySelector('#remove-image').onclick=clearImage;document.querySelector('#ecg-upload').onchange=e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>20*1024*1024){clearImage();alert('Choose PNG, JPG or WebP under 20 MB.');return}if(imageURL)URL.revokeObjectURL(imageURL);imageURL=URL.createObjectURL(f);const im=document.querySelector('#ecg-preview');im.src=imageURL;im.hidden=false;document.querySelector('#remove-image').hidden=false};
const initial=document.querySelector('#result').innerHTML;document.querySelector('#assessment').onreset=()=>{clearImage();document.querySelector('#result').innerHTML=initial};
document.querySelector('#assessment').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const r=WCT.analyze(d);function list(t,a){return a.length?`<h3>${t}</h3><ul>${a.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}document.querySelector('#result').innerHTML=`<div class="eyebrow">ENTERED-FINDING ANALYSIS</div><h2>${r.title}</h2>${r.urgent?`<p class="danger">${r.urgent}</p>`:''}${r.scope?`<p class="notice">${r.scope}</p>`:''}<p class="sequence">${r.sequence}</p>${list('Strong VT findings',r.positive)}${list('Supporting observations',r.support)}${list('Alternative mechanisms',r.alternatives)}${list('Missing information',r.missing)}<p class="muted">No probability is calculated. Confirm the mechanism with clinical assessment and expert ECG review. If WCT remains uncertain, manage as VT.</p><p class="muted">AHA 2025: avoid verapamil/diltiazem in WCT. Adenosine is only a consideration in stable regular monomorphic WCT; avoid in unstable, irregular or polymorphic WCT.</p><button id="print-result" type="button">Print assessment</button>`;document.querySelector('#print-result').onclick=()=>window.print();document.querySelector('#result').scrollIntoView({behavior:'smooth',block:'nearest'})};
